### ISSUE TITLE
Not clear how to use git-upload-release with 2-factor auth

### ISSUE THREAD

**Issue by talex5** [avsm/ocaml-github#38]
Running `git-upload-release` gives:

    $ git-upload-release --help
    Use git-jar to create an `infra` cookie first.

I tried:

    $ git jar show talex5
    Enter Github password: ...
    git-jar: internal error, uncaught exception:
             Failure("HTTP Error 401 Unauthorized\naccess-control-allow-credentials: true\r\n\naccess-control-allow-origin: *\r\n\naccess-control-expose-headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval\r\n\ncontent-length: 160\r\n\ncontent-security-policy: default-src 'none'\r\n\ncontent-type: application/json; charset=utf-8\r\n\ndate: Mon, 03 Nov 2014 14:41:31 GMT\r\n\nserver: GitHub.com\r\n\nstatus: 401 Unauthorized\r\n\nstrict-transport-security: max-age=31536000; includeSubdomains; preload\r\n\nx-content-type-options: nosniff\r\n\nx-frame-options: deny\r\n\nx-github-media-type: github.v3; format=json\r\n\nx-github-otp: required; app\r\n\nx-github-request-id: 524565A9:319B:B78DF8:5457941B\r\n\nx-ratelimit-limit: 60\r\n\nx-ratelimit-remaining: 59\r\n\nx-ratelimit-reset: 1415029291\r\n\nx-xss-protection: 1; mode=block\r\n\n")

Also tried generating a "Personal access token" and using that:

    $ git jar show TOKEN
    Enter Github password: x-oauth-basic
    git-jar: internal error, uncaught exception:
             Failure("HTTP Error 404 Not Found\naccess-control-allow-credentials: true\r\n\naccess-control-allow-origin: *\r\n\naccess-control-expose-headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval\r\n\ncontent-length: 77\r\n\ncontent-security-policy: default-src 'none'\r\n\ncontent-type: application/json; charset=utf-8\r\n\ndate: Mon, 03 Nov 2014 14:43:18 GMT\r\n\nserver: GitHub.com\r\n\nstatus: 404 Not Found\r\n\nstrict-transport-security: max-age=31536000; includeSubdomains; preload\r\n\nx-accepted-oauth-scopes:  \r\n\nx-content-type-options: nosniff\r\n\nx-frame-options: deny\r\n\nx-github-media-type: github.v3; format=json\r\n\nx-github-request-id: 524565A9:319F:44651E1:54579486\r\n\nx-oauth-scopes: gist, repo, user\r\n\nx-ratelimit-limit: 5000\r\n\nx-ratelimit-remaining: 4999\r\n\nx-ratelimit-reset: 1415029398\r\n\nx-xss-protection: 1; mode=block\r\n\n")

I'm not sure what I'm supposed to do here...

**Comment by michipili** [comment]
I had the same issue. As a workaround I manually generated an authentication token and wrote a small program to put it in the jar:

```ocaml
let token_str = "AUTHENTICATION-TOKEN"

let auth =
  let open Github_t in {
    auth_scopes = [];
    auth_token = token_str;
    auth_app = {
      app_name = "APPLICATION-NAME";
      app_url = "APPLICATION-URL";
    };
    auth_id = TOKEN-ID;
    auth_url = AUTH-URL"";
    auth_note = None;
    auth_note_url = None;
  }

let t () =
  let open Lwt in
  Github_cookie_jar.init ()
  >>= Github_cookie_jar.save ~name:"COOKIE-NAME" ~auth
  >>= fun _ -> return ()

let () =
  Lwt_main.run (t())
```

It seems that most of the fields in the `auth` structure are informational, the first time I used this, I only filled in the `AUTHENTICATION-TOKEN` and the `AUTH-SCOPES`.

You can generate such a token by visiting your *Personal Settings* and then the *Applications* tab.
