### ISSUE TITLE
FYI: Upcoming GitHub API changes

### ISSUE THREAD

**Issue by amirmc** [avsm/ocaml-github#47]
*received via email - not sure if this affects anything*

****

#### Breaking changes to some Organizations APIs coming in five weeks (February 24)

If your application uses any of the following APIs, then you are affected by this change:

- APIs for managing your organization's admins through the Owners team
- The List your repositories API
- The List your organizations API
- The List user organizations API

If your application uses these APIs, we urge you to update your application as soon as possible. Read the recent announcement for more details on the changes.

**Comment by dsheets** [comment]
Where's the recent announcement? The blog is silent on this and they won't let me be in the developers' program without paying them.

**Comment by amirmc** [comment]
I've forwarded you the email (was to much effort to copy paste all the links here).  One of the early links points to: https://developer.github.com/changes/2015-01-19-an-integrators-guide-to-organization-application-policies/  (though I've not read anything closely)

**Comment by dsheets** [comment]
These are all semantic changes that this library's consumers would have to adjust to. I don't see any changes that modify the endpoints, types, conventions, etc. This issue can be closed.
