### ISSUE TITLE
Issue do not have any date attached

### ISSUE THREAD

**Issue by michipili** [avsm/ocaml-github#50]
The type `Github_t.issue` does not have any date field, but the Github API returns three dates or date options attached to each issue. These look like:

```
    "created_at": "2015-02-09T15:59:17Z",
    "updated_at": "2015-02-09T16:16:52Z",
    "closed_at": null,
```

It would be great to have access to this information, even in the simple form of `bytes` or `bytes` option. Is there any plan to add these? Maybe I could help here but I would probably need a kind of mentorship.

----
I used the following code to convert similar timestamps to seconds since EPOCH:

```
let timestamp_to_secs timestamp =
  let convert year month day hour minute seconds =
    let open Unix in
    let unixtm = {
      tm_sec = 0;
      tm_min = minute;
      tm_hour = hour;
      tm_mday = day;
      tm_mon = month;
      tm_year = year - 1900;
      tm_wday = 0;
      tm_yday = 0;
      tm_isdst = false;
    } in
    let (secs, _) = Unix.mktime unixtm in
    secs +. seconds
  in
  let open Scanf in
  sscanf timestamp "%d-%d-%dT%d:%d:%fZ" convert
```

The timestamps I have contained floating seconds, which required the special handling of seconds that you see. If you feel that providing Unix dates would be more useful than text strings, the above snippet could be used as a starting point.

**Comment by dsheets** [comment]
It looks like #51 exposed dates as strings so this particular issue can be closed. Perhaps users should be directed to <https://github.com/sagotch/ISO8601.ml> for parsing? Or maybe we should depend on that? Feel free to open a new issue regarding date parsing.

**Comment by michipili** [comment]
Sorting and printing can be accomplished on the textual representation for dates and if we parse dates, there is no clear canonical representation of dates we should pick. I think we should not add a dependency which would not make sense for all the users. Users may want to use Unix times, floats or types defined by the excellent calendar library by Julien Signoles.

If we were to provide parsing, we could go away with the simple scanf code I attached here, but this is really a 2-liner, so we probably do not need to bother! :D
