### ISSUE TITLE
Building on Travis always fails for opam 1.1.0

### ISSUE THREAD

**Issue by michipili** [avsm/ocaml-github#54]
We have this error message

```
Updating ~/.opam/packages/ ...
[ERROR] Your version of OPAM (1.1.2-rc3) is not recent enough to read ~/.opam/repo/default/packages/ago/ago.0.1/opam. Upgrade OPAM to a more recent version (at least 1.2) to read this file correctly.
<… dozens of similar error message…>
```

It seems that the file format changed from 1.1.0 to 1.2.0 in and that packages found in the repository are not compatible with 1.1.0. We should remove spam 1.1.0 from the integration script.

**Comment by avsm** [comment]
Yep, this needs to be fixed by using the centrally sourced Travis scripts from http://github.com/ocaml/ocaml-travisci-skeleton

**Comment by michipili** [comment]
Okay, I will take a look at that. Otherwise, CI is not *that* useful. :D

**Comment by avsm** [comment]
indeed!  OPAM 1.1 work if you do "opam init && opam update" as there is a rewrite in place, but we only really test with OPAM 1.2 these days, which the central skeleton scripts take care of.

**Comment by michipili** [comment]
Just to be sure, should OPAM 1.1 be tested in CI or should it be removed?

**Comment by michipili** [comment]
It seems we can close this issue now.
