### ISSUE TITLE
Missing search API

### ISSUE THREAD

**Issue by samoht** [avsm/ocaml-github#56]
Would be cool to be able to run search commands through the command-line, using https://developer.github.com/v3/search/

bonus points if you can specify the search parameters for the language type easily.

**Comment by samoht** [comment]
My (very specific) use-case: in https://github.com/github/linguist/pull/2270 someone wanted all the repositories containing the word "OCaml" but categorised as developed using Standard ML as a CSV file. Would be nice to be able to do this in a few lines with a small script using `ocaml-github`.

**Comment by dsheets** [comment]
There are 4 search API endpoints for repositories, code, issues, and users. I've implemented the repository search endpoint (b6e1a31) and can run queries like the one you require using a command-line tool that's in development and will be pushed shortly.

I will leave the remaining 3 endpoints for future work. If you'd like to track their implementation, please open new issues regarding those API fragments.

**Comment by dsheets** [comment]
https://github.com/github/linguist/issues/2208#issuecomment-90951288 contains the current query as run from 1a39617.

**Comment by samoht** [comment]
sweet, thanks!

**Comment by samoht** [comment]
> I will leave the remaining 3 endpoints for future work. If you'd like to track their implementation, please open new issues regarding those API fragments.

That sounds good, thanks for looking into this.
